# Generated by Django 2.2.7 on 2020-03-10 20:10

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('buy_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('music_detail', DjangoUeditor.models.UEditorField(default='', verbose_name='歌曲详情')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否广告位')),
                ('image', models.ImageField(upload_to='music/%Y/%m', verbose_name='封面图')),
                ('music_transactionHash', models.CharField(max_length=128, verbose_name='交易hash')),
                ('music_name', models.CharField(max_length=50, verbose_name='歌曲名')),
                ('music_desc', models.CharField(max_length=300, verbose_name='歌曲描述')),
                ('music_times', models.IntegerField(default=0, verbose_name='歌曲时长(分钟数)')),
                ('music_bcId', models.CharField(max_length=32, verbose_name='歌曲上链id')),
                ('music_status', models.BooleanField(default=True, verbose_name='歌曲状态')),
                ('music_price1', models.CharField(default='', max_length=128, verbose_name='个人价格')),
                ('music_price2', models.CharField(default='', max_length=128, verbose_name='版权价格1')),
                ('music_price3', models.CharField(default='', max_length=128, verbose_name='版权价格2')),
                ('music_price4', models.CharField(default='', max_length=128, verbose_name='版权价格3')),
                ('music_price5', models.CharField(default='', max_length=128, verbose_name='版权价格4')),
                ('music_price6', models.CharField(default='', max_length=128, verbose_name='版权价格5')),
                ('music_hashLink', models.CharField(max_length=64, verbose_name='ipfshash')),
                ('music_demoLink', models.CharField(max_length=64, verbose_name='ipfs试听音乐hash')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='版权拥有者')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': '课程标签',
                'verbose_name_plural': '课程标签',
            },
        ),
    ]
