# Generated by Django 2.2.7 on 2020-03-13 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200313_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': '歌曲标签',
                'verbose_name_plural': '歌曲标签',
            },
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
