# Generated by Django 2.2.7 on 2020-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200313_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictag',
            old_name='course',
            new_name='music',
        ),
    ]
