# Generated by Django 2.2.7 on 2020-03-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200313_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_times',
            field=models.IntegerField(default=0, verbose_name='歌曲时长(秒)'),
        ),
    ]
