# Generated by Django 2.2.7 on 2020-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200313_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictag',
            name='tag',
            field=models.IntegerField(verbose_name='标签'),
        ),
    ]
