# Generated by Django 2.2.7 on 2020-03-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200313_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictag',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='标签名'),
        ),
    ]
