# Generated by Django 2.2.7 on 2020-03-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_musictag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictag',
            name='name',
        ),
    ]
