# Generated by Django 2.2.7 on 2020-03-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_musictag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': '音乐版权信息', 'verbose_name_plural': '音乐版权信息'},
        ),
    ]
