# Generated by Django 2.2.7 on 2020-04-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_musiccomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiccomments',
            old_name='course',
            new_name='music',
        ),
    ]
