# Generated by Django 2.2.7 on 2020-04-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200401_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musiccomments',
            options={'verbose_name': '音乐评论', 'verbose_name_plural': '音乐评论'},
        ),
        migrations.AlterField(
            model_name='musiccomments',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='音乐'),
        ),
    ]
