# Generated by Django 2.2.7 on 2020-04-09 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20200404_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithoutMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('owneraddress', models.CharField(default='', max_length=42, verbose_name='账户地址')),
                ('buy_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('music_transactionHash', models.CharField(max_length=128, verbose_name='交易hash')),
                ('music_name', models.CharField(max_length=50, verbose_name='歌曲名')),
                ('music_desc', models.CharField(max_length=300, verbose_name='歌曲描述')),
                ('music_times', models.IntegerField(default=0, verbose_name='歌曲时长(秒)')),
                ('music_bcId', models.CharField(max_length=32, verbose_name='歌曲上链id')),
                ('music_status', models.BooleanField(default=True, verbose_name='歌曲状态')),
                ('music_price1', models.CharField(default='', max_length=128, verbose_name='个人价格')),
                ('music_price2', models.CharField(default='', max_length=128, verbose_name='版权价格1')),
                ('music_price3', models.CharField(default='', max_length=128, verbose_name='版权价格2')),
                ('music_price4', models.CharField(default='', max_length=128, verbose_name='版权价格3')),
                ('music_price5', models.CharField(default='', max_length=128, verbose_name='版权价格4')),
                ('music_price6', models.CharField(default='', max_length=128, verbose_name='版权价格5')),
                ('music_hashLink', models.CharField(max_length=64, verbose_name='ipfshash')),
                ('music_demoLink', models.CharField(max_length=64, verbose_name='ipfs试听音乐hash')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
