# Generated by Django 2.2.7 on 2020-04-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_withoutmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='keyfile',
            field=models.FileField(default='', upload_to='music/key/%Y/%m', verbose_name='上传加密文件'),
        ),
    ]
