# Generated by Django 2.2.7 on 2020-04-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_music_keyfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withoutmusic',
            name='buy_nums',
        ),
    ]
