# Generated by Django 2.2.7 on 2020-04-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_withoutmusic_buy_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withoutmusic',
            name='music_times',
        ),
    ]
