# Generated by Django 2.2.7 on 2020-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_remove_withoutmusic_music_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='timestamp',
            field=models.CharField(default='', max_length=128, verbose_name='上链时间戳'),
        ),
        migrations.AddField(
            model_name='withoutmusic',
            name='timestamp',
            field=models.CharField(default='', max_length=128, verbose_name='上链时间戳'),
        ),
    ]
