# Generated by Django 2.2.7 on 2020-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20200409_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='withoutmusic',
            name='timestamp',
        ),
    ]
