# Generated by Django 2.2.7 on 2020-04-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200409_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='buy_nums',
        ),
        migrations.RemoveField(
            model_name='music',
            name='click_nums',
        ),
        migrations.RemoveField(
            model_name='music',
            name='fav_nums',
        ),
    ]
