# Generated by Django 2.2.7 on 2020-04-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20200412_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMusic',
            fields=[
            ],
            options={
                'verbose_name': '首页轮播图音乐',
                'verbose_name_plural': '首页轮播图音乐',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.music',),
        ),
    ]
