# Generated by Django 2.2.7 on 2020-04-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_bannermusic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermusic',
            options={'verbose_name': '首页推荐音乐', 'verbose_name_plural': '首页推荐音乐'},
        ),
        migrations.AlterModelOptions(
            name='withoutmusic',
            options={'verbose_name': '未归入系统音乐', 'verbose_name_plural': '未归入系统音乐'},
        ),
    ]
