# Generated by Django 2.2.7 on 2020-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20200418_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_status',
            field=models.BooleanField(default=False, verbose_name='歌曲状态'),
        ),
    ]
