# Generated by Django 2.2.7 on 2020-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20200419_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_status',
            field=models.IntegerField(default=0, verbose_name='歌曲状态'),
        ),
    ]
