# Generated by Django 2.2.7 on 2020-03-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200310_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='publickey',
            field=models.CharField(default='', max_length=500, verbose_name='账户公钥'),
        ),
    ]
