# Generated by Django 2.2.7 on 2020-03-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200311_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=42, verbose_name='账户地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='publickey',
            field=models.CharField(default='', max_length=120, verbose_name='账户公钥'),
        ),
    ]
