# Generated by Django 2.2.7 on 2020-03-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200311_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='publickey',
            field=models.CharField(default='', max_length=130, verbose_name='账户公钥'),
        ),
    ]
