# Generated by Django 2.2.7 on 2020-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200311_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_producter',
            field=models.BooleanField(default=False, verbose_name='是否版权发布者'),
        ),
    ]
