# Generated by Django 2.2.7 on 2020-04-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200321_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
    ]
