# Generated by Django 2.2.7 on 2020-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200404_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='账户地址'),
        ),
    ]
