# Generated by Django 2.2.7 on 2020-04-18 01:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUser',
            fields=[
            ],
            options={
                'verbose_name': '音乐制作人',
                'verbose_name_plural': '音乐制作人',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
