# Generated by Django 2.2.7 on 2020-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_productuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=42, null=True, unique=True, verbose_name='账户地址'),
        ),
    ]
