# Generated by Django 2.2.7 on 2020-03-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200315_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='purchase_status',
            field=models.IntegerField(default=0, verbose_name='0未购买1未付款2未发送密钥服务器3成功'),
        ),
    ]
