# Generated by Django 2.2.7 on 2020-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_usermusic_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='purchase_isUpdate',
            field=models.BooleanField(default=False, verbose_name='是否升级'),
        ),
    ]
