# Generated by Django 2.2.7 on 2020-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_usermusic_purchase_isupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='music_price',
            field=models.CharField(default='', max_length=128, verbose_name='价格'),
        ),
    ]
