# Generated by Django 2.2.7 on 2020-03-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20200320_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='timestamp',
            field=models.CharField(default='', max_length=128, verbose_name='上链时间戳+产品授权时间戳'),
        ),
    ]
