# Generated by Django 2.2.7 on 2020-04-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_usermusic_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicComments',
        ),
    ]
