# Generated by Django 2.2.7 on 2020-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_delete_musiccomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='purchase_status',
            field=models.IntegerField(default=0, verbose_name='0未付款1未发送密钥服务器2成功3失效'),
        ),
    ]
