# Generated by Django 2.2.7 on 2020-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20200407_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='purchase_isUpdate',
            field=models.IntegerField(default=0, verbose_name='是否升级'),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='purchase_status',
            field=models.IntegerField(default=0, verbose_name='0未付款1未发送密钥服务器2成功3失效4为发送密钥升级'),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='timestamp',
            field=models.CharField(default='', max_length=128, verbose_name='上链时间戳'),
        ),
    ]
