# Generated by Django 2.2.7 on 2020-04-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20200407_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='purchase_status',
            field=models.IntegerField(default=0, verbose_name='0未付款1未发送密钥服务器2成功3失效4为发送密钥升级5删除6退款'),
        ),
    ]
