# Generated by Django 2.2.7 on 2020-04-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_witchoutusermusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='witchoutusermusic',
            name='boughtaddress',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='购买钱包地址'),
        ),
    ]
