# Generated by Django 2.2.7 on 2020-04-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_witchoutusermusic_boughtaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='witchoutusermusic',
            name='product_bcId',
            field=models.CharField(default='', max_length=32, verbose_name='购买凭证id'),
        ),
    ]
