# Generated by Django 2.2.7 on 2020-04-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_witchoutusermusic_product_bcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='witchoutusermusic',
            old_name='boughtaddress',
            new_name='bought_address',
        ),
    ]
