# Generated by Django 2.2.7 on 2020-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20200411_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='key_ipfshash',
            field=models.CharField(default='', max_length=64, verbose_name='keyipfshash'),
        ),
    ]
