# Generated by Django 2.2.7 on 2020-04-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_usermusic_key_ipfshash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
