# Generated by Django 2.2.7 on 2020-04-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_delete_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermusic',
            options={'verbose_name': '用户系统购买管理', 'verbose_name_plural': '用户系统购买管理'},
        ),
        migrations.AlterModelOptions(
            name='witchoutusermusic',
            options={'verbose_name': '系统外购买查看', 'verbose_name_plural': '系统外购买查看'},
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='购买的音乐'),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='purchase_status',
            field=models.IntegerField(default=0, verbose_name='购买状态'),
        ),
        migrations.AlterField(
            model_name='witchoutusermusic',
            name='product_bcId',
            field=models.CharField(default='', max_length=32, verbose_name='购买版权id'),
        ),
    ]
