# Generated by Django 2.2.7 on 2020-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20200418_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
    ]
