# Generated by Django 2.2.7 on 2020-04-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='projectname',
            field=models.CharField(default='', max_length=128, verbose_name='授权项目名称'),
        ),
    ]
